### ISSUE TITLE
Archive Page | Suggestion to show new posts first

### ISSUE THREAD

**Issue by al3xt96** [johnnyreilly/blog.johnnyreilly.com#327]
Hi John, 

https://blog.johnnyreilly.com/archive 

On your archive page, I see that you're first showing results from oldest to newest. Have you considered perhaps chaining the order? 
If so, I would like to help out with that by opening the pull request here for this topic

Best,
Alex

**Comment by johnnyreilly** [comment]
Hi Alex, 

That's very kind!

Whilst I originally wrote a post about creating a blog archive for a Docusaurus site: https://blog.johnnyreilly.com/2021/05/01/blog-archive-for-docusaurus/

This was picked up and implemented in Docusaurus itself here:

https://github.com/facebook/docusaurus/pull/5428

So if you wanted to make that change (and I think it's a good idea BTW) - you'd want to make it in Docusaurus itself.

**Comment by al3xt96** [comment]
Hi John,

Thanks for the quick answer here. I've quickly went over the links you've sent but will need to read them in-depth. 

I think I can close this issue now, since you've made a suggestion to do it directly in Docusaurus itself.
